// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKi7CFGaXehmpiDxtxdeSKoKh3w41IYIc',
    appId: '1:468648793842:web:99f0f4cd0766d3957ca26b',
    messagingSenderId: '468648793842',
    projectId: 'firebasecrudseries',
    authDomain: 'fir-crudseries.firebaseapp.com',
    storageBucket: 'firebasecrudseries.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdenGPjaes8p2df9DLKGxTkE8jxh_QSuE',
    appId: '1:468648793842:android:d209ad6f48c7c27e7ca26b',
    messagingSenderId: '468648793842',
    projectId: 'firebasecrudseries',
    storageBucket: 'firebasecrudseries.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1UcrCbFLGfKdU8fXT8yuNt-KKMNCwkPo',
    appId: '1:468648793842:ios:1f6189e4a1bddf187ca26b',
    messagingSenderId: '468648793842',
    projectId: 'firebasecrudseries',
    storageBucket: 'firebasecrudseries.appspot.com',
    iosClientId: '468648793842-fvv4235i7ec98n5hmas01221dkchnr42.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1UcrCbFLGfKdU8fXT8yuNt-KKMNCwkPo',
    appId: '1:468648793842:ios:1f6189e4a1bddf187ca26b',
    messagingSenderId: '468648793842',
    projectId: 'firebasecrudseries',
    storageBucket: 'firebasecrudseries.appspot.com',
    iosClientId: '468648793842-fvv4235i7ec98n5hmas01221dkchnr42.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
